language: scala

before_install:
  - export TRAVIS_BRANCH=`echo $TRAVIS_BRANCH | sed 's%[/_]%-%g'`

script:
  - sbt -DsparkVersion=$SPARK_VERSION -no-colors test

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
    - $HOME/.coursier

env:
  matrix:
    - SPARK_VERSION=2.2.0
    - SPARK_VERSION=2.1.0
    - SPARK_VERSION=2.2.0
    - SPARK_VERSION=2.3.0
